[package]
name = "fem"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"

[workspace]
members = ["fem-proc"]

[dependencies]
num-complex = { version = "0.4.0", optional = true }
serde = { version = "1.0.119", features = ["derive"] }
serde-pickle = "0.6.2"
simple_logger = "1.11.0"
structopt = "0.3.21"
fem-proc = { path = "fem-proc" }
nalgebra = { version = "0.29.0" , features = ["rand"] }
env_logger = "0.9.0"
log = "0.4.14"
rayon = "1.5.1"
spade = "1.8.2"
bincode = "1.3.3"
triangle-rs = "0.1.0"
geotrans = "0.1.0"
complot = { version = "0.3.1", features = ["png"] }
dosio = { version = "0.1.2", optional = true }

[features]
dos = ["dosio", "num-complex"]

[dev-dependencies]
plotters = "0.3.0"
#datax = { path = "../datax" }
rstar = "0.8.2"
rayon = "1.5.0"
rustfft = "5.0.1"
csv = "1.1.5"

#[profile.release]
#debug = true
