[package]
name = "gmt-fem"
version = "0.2.2"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"
license = "MIT"
description = "Giant Magellan Telescope Finite Element Model"
repository = "https://github.com/rconan/fem"
documentation = "https://docs.rs/gmt-fem"
readme = "README.md"
categories = ["science", "simulation"]
keywords = ["telescope", "astronomy"]

[dependencies]
num-complex = { version = "0.4.0" }
serde = { version = "1.0.119", features = ["derive"] }
serde-pickle = "0.6.2"
simple_logger = "1.11.0"
structopt = "0.3.21"
fem-macros = { path = "fem-macros", version = "^0.2"}
nalgebra = { version = "^0.30" , features = ["rand"] }
env_logger = "0.9.0"
log = "0.4.14"
rayon = "1.5.1"
bincode = "1.3.3"
geotrans = "0.1.0"

[dev-dependencies]
plotters = "0.3.0"
#datax = { path = "../datax" }
rstar = "0.8.2"
rayon = "1.5.0"
rustfft = "5.0.1"
csv = "1.1.5"
spade = "1.8.2"
triangle-rs = "0.1.2"
complot = { version = "0.3.1", features = ["png"] }
zip = "0.5.13"
anyhow = "1.0.51"
parquet = "6.3.0"
arrow = "6.3.0"
