[package]
name = "fem"
version = "0.1.0"
authors = ["Rod Conan <rconan@gmto.org>"]
edition = "2018"

[dependencies]
#dosio = { git = "https://github.com/rconan/dosio.git", branch = "main" }
dosio = { path = "../dosio" , optional = true }
log = { version = "0.4.14", optional = true }
nalgebra = "0.26.2"
num-complex = { version = "0.4.0", optional = true }
rayon = { version = "1.5.1", optional = true }
serde = { version = "1.0.119", features = ["derive"] }
serde-pickle = "0.6.2"

[features]
dos = ["dosio", "rayon", "log", "num-complex"]

[dev-dependencies]
plotters = "0.3.0"
datax = { path = "../datax" }
complot = { git = "https://github.com/rconan/complot.git", branch = "main" }
geotrans = { git = "https://github.com/rconan/geotrans.git", branch = "main" }
spade = "1.8.2"
nalgebra = "0.24.0"
rstar = "0.8.2"
rayon = "1.5.0"
rustfft = "5.0.1"
csv = "1.1.5"

#[profile.release]
#debug = true
